source_sh ${srcdir}/emulparams/elf_i386.sh

TEXT_START_ADDR=0x00000000
MAXPAGESIZE=16
EMBEDDED=1

DYNAMIC_LINK=false
unset GENERATE_COMBRELOC_SCRIPT
unset GENERATE_PIE_SCRIPT
unset GENERATE_SHLIB_SCRIPT
